default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  database: db/test.sqlite3

development:
  <<: *default
  database: db/development.sqlite3

staging:
  <<: *default
  host:     <%= ENV['STAGING_SIPS_HOSTNAME'] %>
  port:     <%= ENV['STAGING_SIPS_PORT'] %>
  database: <%= ENV['STAGING_SIPS_DB_NAME'] %>
  username: <%= ENV['STAGING_SIPS_USERNAME'] %>
  password: <%= ENV['STAGING_SIPS_PASSWORD'] %>


production:
  <<: *default
  host:     <%= ENV['PRODUCTION_SIPS_HOSTNAME'] %>
  port:     <%= ENV['PRODUCTION_SIPS_PORT'] %>
  database: <%= ENV['PRODUCTION_SIPS_DB_NAME'] %>
  username: <%= ENV['PRODUCTION_SIPS_USERNAME'] %>
  password: <%= ENV['PRODUCTION_RDS_PASSWORD'] %>
